language: python
fast_finish: true

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.7
    - os: osx
      language: generic

env:
    GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/.gcloud-credentials.json

before_install:
  - openssl aes-256-cbc -K $encrypted_1637a71a6097_key -iv $encrypted_1637a71a6097_iv -in .gcloud-credentials.json.enc -out .gcloud-credentials.json -d
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository -y ppa:ubuntugis/ppa; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gdal-bin; fi

install:
  - pip3 install numpy
  - pip3 install . --no-binary rasterio --user

script:
  - bash tests.sh
  - python3 tsd/test_search_scihub.py
  - python3 tsd/test_search_devseed.py
