fast_finish: true

matrix:
  include:
    - os: osx
      language: generic

env:
    GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/.gcloud-credentials.json

before_install:
    openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in .gcloud-credentials.json.enc -out .gcloud-credentials.json -d

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://www.kyngchaos.com/files/software/frameworks/GDAL_Complete-2.3.dmg; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then X=$(echo `hdiutil mount GDAL_Complete-2.3.dmg | tail -1 | awk '{$1=$2=""; print $0}'` | xargs -0 echo) && sudo installer -pkg "${X}/"Install\ GDAL\ Complete.pkg -target /; export PATH="/Library/Frameworks/GDAL.framework/Programs:$PATH"; fi
  - pip3 install numpy
  - pip3 install . --no-binary rasterio --user

script:
  - bash tests.sh
  - python3 tsd/test_search_scihub.py
  - python3 tsd/test_search_devseed.py
