language: python
fast_finish: true

if: tag IS blank

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.7
    - os: osx
      language: generic

env:
    GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/.gcloud-credentials.json CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

before_install:
  - openssl aes-256-cbc -K $encrypted_1637a71a6097_key -iv $encrypted_1637a71a6097_iv -in .gcloud-credentials.json.enc -out .gcloud-credentials.json -d

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        # use a virtual environment to avoid having to do "pip3 install --user"
        python3 -m venv venv
        source venv/bin/activate
    fi
  - pip install -e .

script:
  - bash tests.sh
  - python3 tsd/test_search_scihub.py
  - python3 tsd/test_search_devseed.py
